### ISSUE TITLE
Highlighting broken when having parenthesis inside the string

### ISSUE THREAD

**Issue by maximsch2** [JuliaLang/atom-language-julia#11]
Consider this code:
```
f(g("($A)"))
f(g("($B)"))
f(g("($C)"))
```

The highlighting it produces is broken (closing parenthesis is matched inside the string):
![screenshot - 06292015 - 03 15 31 pm](https://cloud.githubusercontent.com/assets/464680/8419833/ef1b53c6-1e71-11e5-87f1-73d9eab79d8e.png)

**Comment by spencerlyon2** [comment]
Are you using v0.2.0?

When I do this, I get the following highlighting:

![screen shot 2015-06-30 at 9 12 31 am](https://cloud.githubusercontent.com/assets/1001948/8431527/29773544-1f08-11e5-97f1-8d99e15a50e8.png)

**Comment by maximsch2** [comment]
Oops, it looks like I've I was actually using another package and this is just a duplicate of https://github.com/tpoisot/language-julia/issues/8 . Sorry about that. Is there a consensus of which package is going to be a long-term main one for Julia support in Atom?

**Comment by spencerlyon2** [comment]
No problem. This package will be officially supported long-term.

Part of the conversation regarding that decision is is in #2, other parts are in [this](https://groups.google.com/forum/#!topic/julia-users/YPCAS6veMLY) julia-users thread

**Comment by maximsch2** [comment]
```
apm remove language-julia
apm install language-julia
```
fixed the problem. Thanks! It might be a good idea to think about some kind of automatic transition or at least a message for people on the old plugin that this is the official one now.

**Comment by spencerlyon2** [comment]
Great idea.

Would you mind putting those instructions in the readme and issuing a pull request?



// Spencer
