### ISSUE TITLE
Plugin doesn't work with Atom 1.0

### ISSUE THREAD

**Issue by samuela** [JuliaLang/atom-language-julia#12]
Enabling the plugin fails with error: `Uncaught Error: spawn julia ENOENT (events.js)`.

**Comment by spencerlyon2** [comment]
Hmm, seems strange as we are not spawning anything (yet) in this package. 

Any chance it was https://github.com/vindvaki/atom-autocomplete-julia?

**Comment by samuela** [comment]
Hmm, that's possible. I'm not sure exactly.

**Comment by spencerlyon2** [comment]
Is this still an issue?

**Comment by samuela** [comment]
I'm haven't come across any issues recently, so I guess not.

**Comment by spencerlyon2** [comment]
Glad it works. 

Thanks @samuela
