### ISSUE TITLE
@doc is not properyl scopped

### ISSUE THREAD

**Issue by tpoisot** [JuliaLang/atom-language-julia#30]
Whenever it type `doc<Tab>`, the docstring snippet from `language-julia` is inserted.

**Comment by spencerlyon2** [comment]
I'm a bit confused. Is this about a snippet or scoping?

**Comment by tpoisot** [comment]
The snippets have scoping, so that when I'm editing a markdown document, for example, the python snippets have no effect. The `doc` snippet of julia is not properly scoped (`*`), so it is evaluated for all languages, which is not what it should be. Let me submit a PR.

**Comment by spencerlyon2** [comment]
Ahh this makes sense. Thanks for clarifying.
