### ISSUE TITLE
BUG: currently indexing an array thinks the array is a type

### ISSUE THREAD

**Issue by spencerlyon2** [JuliaLang/atom-language-julia#41]
In 

```
xs[i]
```

we would have that `xs` is scoped as a type. I can think of a few instances where we want this to be a type:

- `Float64[]` -- creating an empty, typed array
- `Float64[1, 2, 3]` -- creating a non-empty, typed array
- `Float64[f(i) for i in x]`-- typed comprehension

Not sure how we separate case 2 and indexing...

Maybe we just wait until when (if?) Jeff wins and we moved the type for typed comprehensions/arrays to the end (e.g. `[...]T` instead of the current `T[...]`)

**Comment by garborg** [comment]
Hmmm... without getting into naming conventions, I don't see a good way around -- I added this type identification, but I'm for just removing it for now.

**Comment by one-more-minute** [comment]
Since typed array calls (empty or not) are actually just `getindex` calls anyway there's no way to separate the two cases. Arguably, since `Function`s, `Type`s and `Module`s are really just types of run-time value, trying to guess their presence from syntax is a non-starter – like trying to guess whether `x` is an `Int` from syntax alone.

I don't think it would be so bad to just highlight identifiers beginning with a capital letter as types. Yes, that technically means people can highlight their integer as a type by defining `Foo = 1`, but IMO the (very minimal) consequences of doing that are on them.

**Comment by garborg** [comment]
But what about differentiating between `MyType` and `MY_INDEXABLE_CONST`? It's impossible do assign acronyms or single-letter names to one bin or the other with certainty.

**Comment by one-more-minute** [comment]
Types and consts could just have the same non-default colouring. After all they are both a type of constant :)

It's basically consistent that identifiers with capitals mean "slightly unusual / notable kind of variable". Really we'd be overloading the `type.julia` scope to refer to that, and actual Julia types are a subset. Conceptually, it is at least consistent.

I'm not adamant about it or anything, but for the reasons above I think the only alternative is to avoid differentiating between normal vars and types altogether – and some differentiation seems better than none at all, even if "notable kind of variable" is a relatively broad category.

**Comment by facundoq** [comment]
I think differentiating using a regexp on the convention that types are PascalCase and variables_use_underscores_and_lowercase would work in 99% of my Julia code.

**Comment by jianghaizhu** [comment]
The array indexing highlighted as Type really confused me in my code. Is there any plan to fix this bug? or any workaround at the moment?

**Comment by jianghaizhu** [comment]
Also in the following code

 `convert(Array{T}, r)`

shouldn't `Array{T}` be treated as Type?

**Comment by JeffBezanson** [comment]
I'll put in a vote for not applying coloring unless it is actually correct.

**Comment by pfitzseb** [comment]
Yeah, we just should not color types since it's impossible to tell what they are from syntax alone (and maybe optionally color words in camel case as types).

**Comment by spencerlyon2** [comment]
I agree with what is said here. If anyone has the time to implement this I will happily review a PR, I don't think I'll be able to do it myself.
