### ISSUE TITLE
malformed increaseindent regex

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/atom-language-julia#46]
The [current regex](https://github.com/JuliaLang/atom-language-julia/blob/730060caa53605b4cf4a1addab0f46a540b8ebc9/settings/language-julia.cson#L6) to increase indentation level is
```
^(\\s*|.*=\\s*|.*@\\w*\\s*)(if|while|for|function|stagedfunction|macro|immutable|type|let|quote|try|begin|.*\\)\\s*do|else|elseif|catch|finally)\\b(?!.*\\bend\\b[^\\]]*$).*$
```

Pasting that into http://regexpal.com/ highlights an extra closing paren. I'm not familiar enough with what this regex is supposed to do, but I'm guessing that might be causing some trouble.

**Comment by spencerlyon2** [comment]
Closed by #50
