### ISSUE TITLE
LaTeX -> unicode substitution on <TAB>

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/atom-language-julia#47]
It would be great to have the emacs and REPL functionality for replacing LaTeX commands with the right unicode symbols here, as well.

**Comment by spencerlyon2** [comment]
They used to be here, but since unicode greek letters aren't specific to Julia we moved them to [another pacakge](https://github.com/JunoLab/atom-latex-completions).

If you install that latex-completions package you should be good to go!

**Comment by rhsciss** [comment]
Many Thanks. Worked for me too.
