### ISSUE TITLE
Whitespace in type annotation should be ignored

### ISSUE THREAD

**Issue by H-225** [JuliaLang/atom-language-julia#54]
The following two snippets should be interpreted identically.

```julia
x::UInt8
x   ::   UInt8
```

When you have a function or type constructor which takes lots of arguments, such that you break them up into multiple lines, it is nice to be able to align them. :)

```julia
function doit(
        firstarg :: Int
        second   :: UInt
        third    :: Bool
        forth    :: AbstractArray)

   # function body
end
```

Or, if they are kwargs...

```julia
function doit(;
        firstarg ::           Int = -45
        second   ::          UInt = 247
        third    ::          Bool = true
        forth    :: AbstractArray = [])

   # function body
end
```

**Comment by StefanKarpinski** [comment]
Do you have an example of a case where these do not parse the same?

**Comment by H-225** [comment]
@StefanKarpinski 
Here is an example of what I found it by; though other highlightings exhibit the same trait.

![screenshot 2015-12-28 18 45 30](https://cloud.githubusercontent.com/assets/1348560/12023666/7d50687e-ad93-11e5-8ac9-f3300ae73d1d.png)

**Comment by StefanKarpinski** [comment]
Sorry, I thought this was an issue on https://github.com/JuliaLang/julia and was confused. Carry on.

**Comment by H-225** [comment]
@StefanKarpinski I did wonder. :smile:

**Comment by spencerlyon2** [comment]
I think this is a good idea (the goal should always be to match the actual Julia parser), but don't have time to make the changes myself.

I'd be happy to review a PR though... :wink:
