### ISSUE TITLE
Snippets should expand on Tab only (or this should be configurable)

### ISSUE THREAD

**Issue by yay** [JuliaLang/atom-language-julia#58]
For example, I type this:
```
for i in 1:3
```
hit Enter and get this:
```
for i in 1:condition ? if_true : if_false
```
So I have to hit Esc, then Enter. Really?

Meanwhile, maybe there's a workaround that can be used?

**Comment by one-more-minute** [comment]
If you go into Atom's settings -> packages -> autocomplete-plus and click on `settings`, you should be able to find an option to change this behaviour.

**Comment by spencerlyon2** [comment]
Not exactly an issue with this package, but you can add this to your `~/.atom/config.cson`:

```
  "autocomplete-plus":
    confirmCompletion: "tab"
```

**Comment by yay** [comment]
Oh, sorry, new to Atom. Thanks! Response time was amazing :)

**Comment by one-more-minute** [comment]
We aim to please :)

**Comment by spencerlyon2** [comment]
No problem, enjoy!
