### ISSUE TITLE
Docstring code folding

### ISSUE THREAD

**Issue by Godisemo** [JuliaLang/atom-language-julia#59]
It would be nice to be able to code fold the docstrings.

edit: looks like this is a limitation in atom itself https://github.com/atom/first-mate/issues/48

**Comment by spencerlyon2** [comment]
Sorry for the super delayed response.

I think it might be doable still. I use a package `markdown-writer` that lets me hit TAB on a heading and collapse the whole section. None of the section is indented, so it must be possible.

**Comment by tshort** [comment]
It's definitely doable. I'd like this feature, too. [markdown-folder](https://atom.io/packages/markdown-folder) is a good place to start looking (I've contributed to that).

**Comment by spencerlyon2** [comment]
Done in #64!
