### ISSUE TITLE
BUG: Tab completion of sub modules

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/atom-language-julia#65]
Not sure if this is a problem in this package or somewhere else, but when I try tab-completions of submodules the parent module gets consumed. Eg. - if I'm using `Gadfly` and type `Coord.`, I get a list of completions, select `Cartesian` and hit `<tab>`, then instead of `Coord.Cartesian` I end up with just `Cartesian`

**Comment by MikeInnes** [comment]
I'm assuming that you're using the julia-client package for completions? I couldn't reproduce this on the latest versions + julia 0.5. I don't have Gadfly working there but tried with `Base.DFT.FFTW` and `Blink.AtomShell`.

**Comment by kescobo** [comment]
Ah, so this package doesn't handle completions? I actually don't have julia-client installed. I do have Hydrogen (which uses Jupyter) - is that what's managing completions do you think?

**Comment by MikeInnes** [comment]
I imagine that it's hydrogen in the background, but then the issue could be to do with Hydrogen or IJulia.jl. If you can I recommend testing for this behaviour in IPython proper, otherwise your best bet is to go ahead and open issues for those packages.

**Comment by kescobo** [comment]
OK, thanks - I'll check there. Cheers!
