### ISSUE TITLE
Cannot start Julia within Atom using Juno

### ISSUE THREAD

**Issue by TCEagleInSV** [JuliaLang/atom-language-julia#66]
I have just installed Juno-atom on my windows 7 64bit Pro PC.  Julia version is 0.4.5 and it runs OK in its own window.  I cannot get Juno to recognize the path "C:\Users\Eagle\AppData\Local\Julia-0.4.5\bin\julia.exe"  I have tried "//", "\", "\\", everything I can think of.  It will not recognize the path.

What am I doing wrong?

Thank,

Tom Eagle

**Comment by pfitzseb** [comment]
Are you up-to-date on all relevant Atom pacakges? Did you include the quotes in the setting or is it just `C:\Users\Eagle\AppData\Local\Julia-0.4.5\bin\julia.exe`? What's the exact error you're getting?

**Comment by TCEagleInSV** [comment]
Hi Sebastian,

 

I think I have the most recent packages.  I downloaded them the day I sent the original email.  It is version 1.7.3.  below is a screen shot of the message with the path I have entered in the Julia setup. I use quotes.  Julia exist and in that path because I am using a lot right now.

 

Best,

 

Tom

**Comment by pfitzseb** [comment]
> I use quotes.

Don't :) (Sorry that wasn't clear from my response above.)

**Comment by TCEagleInSV** [comment]
I have tried both a single quote(‘) and a double quote (“).  Neither works…

 

Tom

**Comment by pfitzseb** [comment]
Yes, well, as I said: Don't use quotes. The screenshot didn't come through, btw -- I think that's an issue with replying to GitHub issues by mail.

**Comment by TCEagleInSV** [comment]
Sebastian,

 

I have tried it with and without quotes.  Just doesn’t seem to work.  I have tried it so many different ways it is ridiculous.  Do you think uninstalling and re-installing it would help?  It seems something is wrong as I always get the github installer screen upon my PC startup…

 

Is it OK to delete the .atom directory after uninstalling?

 

Tom

**Comment by pfitzseb** [comment]
Yep, if you reinstall Atom you should definetly delete (or backup) the `.atom` dir.

Just to check: The error you're getting is something similar to this:
![error](https://cloud.githubusercontent.com/assets/6735977/15099780/a4ddec8e-155f-11e6-9bcb-43f8f003d784.PNG)

Also, should you run into the same error after reinstalling: Could you check the devtools console (press `Ctrl+Alt+I` to open it) for any errors?

I wish I could be more helpful, but honestly don't know what could be wrong with your setup...

**Comment by spencerlyon2** [comment]
Closing here as it isn't related to this package. If it is still an issue please open at JunoLab/atom-julia-client
