### ISSUE TITLE
Highlighting: Triple quote containing quote character not supported

### ISSUE THREAD

**Issue by NOTtheMessiah** [JuliaLang/atom-language-julia#9]
It seem to treat them as single quotes only.

example: 

    """Contains " quote " characters"""

**Comment by spencerlyon2** [comment]
Thanks for noting. I have a fix implemented. Will package into a new release soon and ping this issue when I've released a new version.

**Comment by spencerlyon2** [comment]
Should be fixed in v0.2.0

**Comment by sbromberger** [comment]
Has 0.2.0 been submitted to apm?

**Comment by spencerlyon2** [comment]
It should have... Are you showing something different?

**Comment by sbromberger** [comment]
Ah, I didn't get the update notification until late last night. I was on 0.1.2 until about 10pm Central Time. All good now!

**Comment by spencerlyon2** [comment]
Excellent. Glad it is working for you.
